export enum ListOfPermissionsEnum {
  create_template = 'create_template',
  find_all_templates = 'find_all_templates',
  find_one_template = 'find_one_template',
  update_template = 'update_template',
  remove_template = 'remove_template',
  create_role = 'create_role',
  find_all_roles = 'find_all_roles',
  find_one_role = 'find_one_role',
  update_role = 'update_role',
  remove_role = 'remove_role',
  create_user = 'create_user',
  find_all_users = 'find_all_users',
  find_one_user = 'find_one_user',
  update_user = 'update_user',
  remove_user = 'remove_user',
  create_permission = 'create_permission',
  find_all_permissions = 'find_all_permissions',
  find_one_permission = 'find_one_permission',
  update_permission = 'update_permission',
  remove_permission = 'remove_permission',
  find_all_audits = 'find_all_audits',
  create_appointment = 'create_appointment',
  find_all_appointments = 'find_all_appointments',
  find_one_appointment = 'find_one_appointment',
  update_appointment = 'update_appointment',
  remove_appointment = 'remove_appointment',
  create_patient = 'create_patient',
  find_all_patients = 'find_all_patients',
  find_one_patient = 'find_one_patient',
  update_patient = 'update_patient',
  remove_patient = 'remove_patient',
  cretae_professional = 'cretae_professional',
  find_all_professionals = 'find_all_professionals',
  find_one_professional = 'find_one_professional',
  update_professional = 'update_professional',
  remove_professional = 'remove_professional',
  create_specialty = 'create_specialty',
  find_all_specialties = 'find_all_specialties',
  find_one_specialty = 'find_one_specialty',
  update_specialty = 'update_specialty',
  remove_specialty = 'remove_specialty',
  create_dependent = 'create_dependent',
  find_all_dependents = 'find_all_dependents',
  find_one_dependent = 'find_one_dependent',
  update_dependent = 'update_dependent',
  remove_dependent = 'remove_dependent',
  create_personSig = 'create_personSig',
  find_external_personSigs = 'find_external_personSigs',
  find_all_personSigs = 'find_all_personSigs',
  find_one_personSig = 'find_one_personSig',
  update_personSig = 'update_personSig',
  remove_personSig = 'remove_personSig',
  create_asset = 'create_asset',
  find_all_assets = 'find_all_assets',
  find_one_asset = 'find_one_asset',
  update_asset = 'update_asset',
  remove_asset = 'remove_asset',
  create_inventory = 'create_inventory',
  find_all_inventories = 'find_all_inventories',
  find_one_inventory = 'find_one_inventory',
  update_inventory = 'update_inventory',
  remove_inventory = 'remove_inventory',
  auth_sing_in = 'auth_sing_in',
  auth_me = 'auth_me',
  create_location = 'create_location',
  find_all_locations = 'find_all_locations',
  find_one_location = 'find_one_location',
  update_location = 'update_location',
  remove_location = 'remove_location',
  // system permissions
  seed_generate_permissions = 'seed_generate_permissions',
  seed_generate_roles = 'seed_generate_roles',
}

export type PermissionType = (typeof PermissionsEnum)[number];

export const PermissionsEnum = [
  ListOfPermissionsEnum.create_template,
  ListOfPermissionsEnum.find_all_templates,
  ListOfPermissionsEnum.find_one_template,
  ListOfPermissionsEnum.update_template,
  ListOfPermissionsEnum.remove_template,
  ListOfPermissionsEnum.create_role,
  ListOfPermissionsEnum.find_all_roles,
  ListOfPermissionsEnum.find_one_role,
  ListOfPermissionsEnum.update_role,
  ListOfPermissionsEnum.create_user,
  ListOfPermissionsEnum.find_all_users,
  ListOfPermissionsEnum.find_one_user,
  ListOfPermissionsEnum.update_user,
  ListOfPermissionsEnum.remove_user,
  ListOfPermissionsEnum.create_permission,
  ListOfPermissionsEnum.find_all_permissions,
  ListOfPermissionsEnum.find_one_permission,
  ListOfPermissionsEnum.update_permission,
  ListOfPermissionsEnum.find_all_audits,
  ListOfPermissionsEnum.create_appointment,
  ListOfPermissionsEnum.find_all_appointments,
  ListOfPermissionsEnum.find_one_appointment,
  ListOfPermissionsEnum.update_appointment,
  ListOfPermissionsEnum.remove_appointment,
  ListOfPermissionsEnum.create_patient,
  ListOfPermissionsEnum.find_all_patients,
  ListOfPermissionsEnum.find_one_patient,
  ListOfPermissionsEnum.update_patient,
  ListOfPermissionsEnum.remove_patient,
  ListOfPermissionsEnum.cretae_professional,
  ListOfPermissionsEnum.find_all_professionals,
  ListOfPermissionsEnum.find_one_professional,
  ListOfPermissionsEnum.update_professional,
  ListOfPermissionsEnum.remove_professional,
  ListOfPermissionsEnum.create_specialty,
  ListOfPermissionsEnum.find_all_specialties,
  ListOfPermissionsEnum.find_one_specialty,
  ListOfPermissionsEnum.update_specialty,
  ListOfPermissionsEnum.remove_specialty,
  ListOfPermissionsEnum.create_dependent,
  ListOfPermissionsEnum.find_all_dependents,
  ListOfPermissionsEnum.find_one_dependent,
  ListOfPermissionsEnum.update_dependent,
  ListOfPermissionsEnum.remove_dependent,
  ListOfPermissionsEnum.create_personSig,
  ListOfPermissionsEnum.find_all_personSigs,
  ListOfPermissionsEnum.find_one_personSig,
  ListOfPermissionsEnum.update_personSig,
  ListOfPermissionsEnum.remove_personSig,
  ListOfPermissionsEnum.create_asset,
  ListOfPermissionsEnum.find_all_assets,
  ListOfPermissionsEnum.find_one_asset,
  ListOfPermissionsEnum.update_asset,
  ListOfPermissionsEnum.remove_asset,
  ListOfPermissionsEnum.create_inventory,
  ListOfPermissionsEnum.find_all_inventories,
  ListOfPermissionsEnum.find_one_inventory,
  ListOfPermissionsEnum.update_inventory,
  ListOfPermissionsEnum.remove_inventory,
  ListOfPermissionsEnum.auth_sing_in,
  ListOfPermissionsEnum.auth_me,
  ListOfPermissionsEnum.create_location,
  ListOfPermissionsEnum.find_all_locations,
  ListOfPermissionsEnum.find_one_location,
  ListOfPermissionsEnum.update_location,
  ListOfPermissionsEnum.remove_location,

  // system permissions
  ListOfPermissionsEnum.seed_generate_roles,
  ListOfPermissionsEnum.seed_generate_permissions,
] as const;

export const groupsOfPermissions = {
  admin: [...PermissionsEnum],
  user: [ListOfPermissionsEnum.auth_sing_in, ListOfPermissionsEnum.auth_me],
  receptionist: [
    ListOfPermissionsEnum.create_appointment,
    ListOfPermissionsEnum.find_all_appointments,
    ListOfPermissionsEnum.find_one_appointment,
    ListOfPermissionsEnum.update_appointment,
    ListOfPermissionsEnum.remove_appointment,
    ListOfPermissionsEnum.find_all_patients,
    ListOfPermissionsEnum.find_one_patient,
    ListOfPermissionsEnum.update_patient,
    ListOfPermissionsEnum.remove_patient,
    ListOfPermissionsEnum.find_all_professionals,
    ListOfPermissionsEnum.find_one_professional,
    ListOfPermissionsEnum.find_all_specialties,
    ListOfPermissionsEnum.find_one_specialty,
    ListOfPermissionsEnum.find_all_dependents,
    ListOfPermissionsEnum.find_one_dependent,
    ListOfPermissionsEnum.update_dependent,
    ListOfPermissionsEnum.find_all_personSigs,
    ListOfPermissionsEnum.find_one_personSig,
    ListOfPermissionsEnum.create_location,
    ListOfPermissionsEnum.find_all_locations,
    ListOfPermissionsEnum.find_one_location,
    ListOfPermissionsEnum.update_location,
  ],
  professional: [
    ListOfPermissionsEnum.find_all_appointments,
    ListOfPermissionsEnum.find_one_appointment,
    ListOfPermissionsEnum.update_appointment,
    ListOfPermissionsEnum.find_all_patients,
    ListOfPermissionsEnum.find_one_patient,
    ListOfPermissionsEnum.update_patient,
    ListOfPermissionsEnum.find_all_dependents,
    ListOfPermissionsEnum.find_one_dependent,
    ListOfPermissionsEnum.update_dependent,
    ListOfPermissionsEnum.find_all_personSigs,
    ListOfPermissionsEnum.find_one_personSig,
  ],
  patient: [
    ListOfPermissionsEnum.find_all_appointments,
    ListOfPermissionsEnum.find_one_appointment,
  ],
};
