services:
  sigsaude-server:
    container_name: sigsaude_server
    image: $IMAGE_TAG
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://$DB_USERNAME:$DB_PASSWORD@$DB_HOST:5432/$DB_DATABASE
      NODE_ENV: 'production'
